import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Baloo_Bhai_2 } from 'next/font/google'
import './globals.css'

//Components
import Navbar from './Components/Navbar'
import { UserProvider } from './Contexts/UserContext'
import { FullSubjectsProvider } from './Contexts/FullSubjects'
//Fonts
const baloo2 = Baloo_Bhai_2({ subsets: ['latin'] })

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <FullSubjectsProvider>
          <Navbar />
          {children}
          </FullSubjectsProvider>
        </UserProvider>
      </body>
    </html>
  )
}
