export const Urls = {
    server:"https://localhost:7184",
    "getuser":"/getuser",
    "login":"/api/Auth/login",
    "logout":"/api/Auth/logout",
    "register":"/api/Auth/register",
    "getallcategories":"/api/General/getcategories",
    "getsubjects":"/api/General/getsubjects",
    "getallsubjects":"/api/General/getallsubjects",
    "getallquestions":"/api/Questions/getallquestions",
    "getsubcategorydetails":"/api/General/getsubcategorydetails",
    "getquestionsset": "/api/Questions/getset",
    "recordmistake":"/api/Questions/recordmistake",
    "savesesiontime":"/api/UserStats/savesesiontime",
    "getuserstats":"/api/UserStats/getuserstats",
    "checkifadmin":"/checkifadmin",
    "addquestion":"/api/Questions/addquestion",
    "addcategory":"/api/Questions/addcategory",
    "addsubcategory":"/api/Questions/addsubcategory",
    "getctyrletymix":"/api/Questions/getfouryearmix",
    "reportmix":"/api/Questions/reportmixresult",
    "getmixesreport":"/api/Mix/getallmixes",
    "getreportdetails":"/api/Mix/getreport",
    "resetpassword":"/api/Auth/resetpassword",
    "updatepassword":"/api/Auth/updatepassword",
    "removequestion":"/api/Questions/removequestion"
}